// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    public partial class Category
    {
        public Category()
        {
            Citations = new HashSet<Citation>();
            InverseParentCategory = new HashSet<Category>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        public string Name { get; set; }
        public int? ParentCategoryId { get; set; }
        [Required]
        [StringLength(450)]
        public string AspNetUserId { get; set; }
        public DateTimeOffset CreatedDate { get; set; }
        [StringLength(255)]
        public string CreatedBy { get; set; }
        public DateTimeOffset? UpdatedDate { get; set; }
        [StringLength(255)]
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }

        [ForeignKey(nameof(AspNetUserId))]
        [InverseProperty("Categories")]
        public virtual AspNetUser AspNetUser { get; set; }
        [ForeignKey(nameof(ParentCategoryId))]
        [InverseProperty(nameof(Category.InverseParentCategory))]
        public virtual Category ParentCategory { get; set; }
        [InverseProperty(nameof(Citation.Category))]
        public virtual ICollection<Citation> Citations { get; set; }
        [InverseProperty(nameof(Category.ParentCategory))]
        public virtual ICollection<Category> InverseParentCategory { get; set; }
    }
}