// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    public partial class Citation
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Body { get; set; }
        [StringLength(255)]
        public string Url { get; set; }
        public bool IsPublic { get; set; }
        [Required]
        [StringLength(450)]
        public string AspNetUserId { get; set; }
        public DateTimeOffset CreatedDate { get; set; }
        [StringLength(255)]
        public string CreatedBy { get; set; }
        public DateTimeOffset? UpdatedDate { get; set; }
        [StringLength(255)]
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }

        [ForeignKey(nameof(AspNetUserId))]
        [InverseProperty("Citations")]
        public virtual AspNetUser AspNetUser { get; set; }
    }
}